### ISSUE TITLE
When do you release your  code ?Thanks

### ISSUE THREAD

**Issue by qiunlp** [varinf/TransformersDataAugmentation#1]

**Comment by varunentropy** [comment]
Hi, 
we are working on it. Legal review is taking longer than expected. Will share the code as soon as we have the approval.

**Comment by timellemeet** [comment]
Hi just wondering if there is any update on this?

**Comment by passionvery** [comment]
When do you release your code ?Thanks

**Comment by good74152** [comment]
I want to know when will you release your code too

**Comment by losimons** [comment]
Any update on this matter? Very interested!

**Comment by varunentropy** [comment]
Sorry for the delay. We released the code.
