### ISSUE TITLE
about BART generation

### ISSUE THREAD

**Issue by qniguoym** [varinf/TransformersDataAugmentation#5]
what is the input of the model when generating？ I feed 'ySEP' as input, but the output is the same as input. Thanks~

**Comment by varunentropy** [comment]
For generation, input is same as the training. We take a sentence x = [x_1, x_2, x_3, ... x_n] and the label y and mask 20% of the tokens and then generate the full sentence. So input to the model is [y, x_1, x_2, `<mask>`, ... x_n] and the expected output is  [y, x_1, x_2, x_3, ... x_n]. For BART, we don't use SEP token. In fact, SEP token is used only for GPT-2 model and for rest of the models, we simply prepend y to x.  

Does it answer your question?

**Comment by qniguoym** [comment]
> For generation, input is same as the training. We take a sentence x = [x_1, x_2, x_3, ... x_n] and the label y and mask 20% of the tokens and then generate the full sentence. So input to the model is [y, x_1, x_2, , ... x_n] and the expected output is [y, x_1, x_2, x_3, ... x_n]. For BART, we don't use SEP token. In fact, SEP token is used only for GPT-2 model and for rest of the models, we simply prepend y to x.
> 
> Does it answer your question?
YES!  Thanks very much~~~

**Comment by varunentropy** [comment]
We open sourced the code. Please review the code and let me know if you still have a question. Thanks
